/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	CompleteStoredSearchDocumentApiService := openapi.NewCompleteStoredSearchDocumentApiService()
	CompleteStoredSearchDocumentApiController := openapi.NewCompleteStoredSearchDocumentApiController(CompleteStoredSearchDocumentApiService)

	NFInstancesStoreApiService := openapi.NewNFInstancesStoreApiService()
	NFInstancesStoreApiController := openapi.NewNFInstancesStoreApiController(NFInstancesStoreApiService)

	StoredSearchDocumentApiService := openapi.NewStoredSearchDocumentApiService()
	StoredSearchDocumentApiController := openapi.NewStoredSearchDocumentApiController(StoredSearchDocumentApiService)

	router := openapi.NewRouter(CompleteStoredSearchDocumentApiController, NFInstancesStoreApiController, StoredSearchDocumentApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
