/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)

// CompleteStoredSearchDocumentApiRouter defines the required methods for binding the api requests to a responses for the CompleteStoredSearchDocumentApi
// The CompleteStoredSearchDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a CompleteStoredSearchDocumentApiServicer to perform the required actions, then write the service results to the http response.
type CompleteStoredSearchDocumentApiRouter interface {
	DeregisterNfInstance(http.ResponseWriter, *http.Request)
	GetNFInstance(http.ResponseWriter, *http.Request)
	RegisterNFInstance(http.ResponseWriter, *http.Request)
	UpdateNFInstance(http.ResponseWriter, *http.Request)
}

// NFInstancesStoreApiRouter defines the required methods for binding the api requests to a responses for the NFInstancesStoreApi
// The NFInstancesStoreApiRouter implementation should parse necessary information from the http request,
// pass the data to a NFInstancesStoreApiServicer to perform the required actions, then write the service results to the http response.
type NFInstancesStoreApiRouter interface {
	GetNFInstance(http.ResponseWriter, *http.Request)
	SearchNFInstances(http.ResponseWriter, *http.Request)
	OptionNFInstances(http.ResponseWriter, *http.Request)
}

// StoredSearchDocumentApiRouter defines the required methods for binding the api requests to a responses for the StoredSearchDocumentApi
// The StoredSearchDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a StoredSearchDocumentApiServicer to perform the required actions, then write the service results to the http response.
type SubscrptionIDDocumentApiRouter interface {
	RemoveSubscription(http.ResponseWriter, *http.Request)
	UpdateSubscription(http.ResponseWriter, *http.Request)
}

// CompleteStoredSearchDocumentApiServicer defines the api actions for the CompleteStoredSearchDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CompleteStoredSearchDocumentApiServicer interface {
	RetrieveCompleteSearch(string, string) (interface{}, error)
}

// NFInstancesStoreApiServicer defines the api actions for the NFInstancesStoreApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NFInstancesStoreApiServicer interface {
	SearchNFInstances(NfType, NfType, string) (interface{}, error)
}

// StoredSearchDocumentApiServicer defines the api actions for the StoredSearchDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type StoredSearchDocumentApiServicer interface {
	RetrieveStoredSearch(string, string) (interface{}, error)
}
