/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// CompleteStoredSearchDocumentApiService is a service that implents the logic for the CompleteStoredSearchDocumentApiServicer
// This service should implement the business logic for every endpoint for the CompleteStoredSearchDocumentApi API.
// Include any external packages or services that will be required by this service.
type CompleteStoredSearchDocumentApiService struct {
}

// NewCompleteStoredSearchDocumentApiService creates a default api service
func NewCompleteStoredSearchDocumentApiService() CompleteStoredSearchDocumentApiServicer {
	return &CompleteStoredSearchDocumentApiService{}
}

// RetrieveCompleteSearch -
func (s *CompleteStoredSearchDocumentApiService) RetrieveCompleteSearch(searchId string, acceptEncoding string) (interface{}, error) {
	// TODO - update RetrieveCompleteSearch with the required logic for this service method.
	// Add api_complete_stored_search_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'RetrieveCompleteSearch' not implemented")
}
