/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PlmnSnssai - List of network slices (S-NSSAIs) for a given PLMN ID
type PlmnSnssai struct {

	PlmnId PlmnId `json:"plmnId"`

	SNssaiList []Snssai `json:"sNssaiList"`

	Nid string `json:"nid,omitempty"`
}
