/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Ipv6PrefixRange - Range of IPv6 prefixes
type Ipv6PrefixRange struct {

	Start Ipv6Prefix `json:"start,omitempty"`

	End Ipv6Prefix `json:"end,omitempty"`
}
