/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ChfServiceInfo - Information of primary and secondary CHF services
type ChfServiceInfo struct {

	PrimaryChfServiceInstance string `json:"primaryChfServiceInstance,omitempty"`

	SecondaryChfServiceInstance string `json:"secondaryChfServiceInstance,omitempty"`
}
