/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// NfProfile - Information of an NF Instance discovered by the NRF
type NfProfile struct {

	NfInstanceId string `json:"nfInstanceId"`

	NfInstanceName string `json:"nfInstanceName,omitempty"`

	NfType NfType `json:"nfType"`

	NfStatus NfStatus `json:"nfStatus"`

	PlmnList []PlmnId `json:"plmnList,omitempty"`

	SNssais []Snssai `json:"sNssais,omitempty"`

	PerPlmnSnssaiList []PlmnSnssai `json:"perPlmnSnssaiList,omitempty"`

	NsiList []string `json:"nsiList,omitempty"`

	// Fully Qualified Domain Name
	Fqdn string `json:"fqdn,omitempty"`

	Ipv4Addresses []string `json:"ipv4Addresses,omitempty"`

	Ipv6Addresses []Ipv6Addr `json:"ipv6Addresses,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Load int32 `json:"load,omitempty"`

	LoadTimeStamp time.Time `json:"loadTimeStamp,omitempty"`

	Locality string `json:"locality,omitempty"`

	Priority int32 `json:"priority,omitempty"`

	UdrInfo UdrInfo `json:"udrInfo,omitempty"`

	UdrInfoExt []UdrInfo `json:"udrInfoExt,omitempty"`

	UdmInfo UdmInfo `json:"udmInfo,omitempty"`

	UdmInfoExt []UdmInfo `json:"udmInfoExt,omitempty"`

	AusfInfo AusfInfo `json:"ausfInfo,omitempty"`

	AusfInfoExt []AusfInfo `json:"ausfInfoExt,omitempty"`

	AmfInfo AmfInfo `json:"amfInfo,omitempty"`

	AmfInfoExt []AmfInfo `json:"amfInfoExt,omitempty"`

	SmfInfo SmfInfo `json:"smfInfo,omitempty"`

	SmfInfoExt []SmfInfo `json:"smfInfoExt,omitempty"`

	UpfInfo UpfInfo `json:"upfInfo,omitempty"`

	UpfInfoExt []UpfInfo `json:"upfInfoExt,omitempty"`

	PcfInfo PcfInfo `json:"pcfInfo,omitempty"`

	PcfInfoExt []PcfInfo `json:"pcfInfoExt,omitempty"`

	BsfInfo BsfInfo `json:"bsfInfo,omitempty"`

	BsfInfoExt []BsfInfo `json:"bsfInfoExt,omitempty"`

	ChfInfo ChfInfo `json:"chfInfo,omitempty"`

	ChfInfoExt []ChfInfo `json:"chfInfoExt,omitempty"`

	UdsfInfo UdsfInfo `json:"udsfInfo,omitempty"`

	UdsfInfoExt []UdsfInfo `json:"udsfInfoExt,omitempty"`

	NwdafInfo NwdafInfo `json:"nwdafInfo,omitempty"`

	NefInfo NefInfo `json:"nefInfo,omitempty"`

	PcscfInfo []PcscfInfo `json:"pcscfInfo,omitempty"`

	HssInfo []HssInfo `json:"hssInfo,omitempty"`

	CustomInfo map[string]interface{} `json:"customInfo,omitempty"`

	RecoveryTime time.Time `json:"recoveryTime,omitempty"`

	NfServicePersistence bool `json:"nfServicePersistence,omitempty"`

	NfServices []NfService `json:"nfServices,omitempty"`

	DefaultNotificationSubscriptions []DefaultNotificationSubscription `json:"defaultNotificationSubscriptions,omitempty"`

	LmfInfo LmfInfo `json:"lmfInfo,omitempty"`

	GmlcInfo GmlcInfo `json:"gmlcInfo,omitempty"`

	SnpnList []PlmnIdNid `json:"snpnList,omitempty"`

	NfSetIdList []string `json:"nfSetIdList,omitempty"`

	ServingScope []string `json:"servingScope,omitempty"`

	LcHSupportInd bool `json:"lcHSupportInd,omitempty"`

	OlcHSupportInd bool `json:"olcHSupportInd,omitempty"`
}
