/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IpEndPoint - IP addressing information of a given NFService; it consists on, e.g. IP address, TCP port, transport protocol...
type IpEndPoint struct {

	Ipv4Address string `json:"ipv4Address,omitempty"`

	Ipv6Address Ipv6Addr `json:"ipv6Address,omitempty"`

	Transport TransportProtocol `json:"transport,omitempty"`

	Port int32 `json:"port,omitempty"`
}
