/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AmfInfo - Information of an AMF NF Instance
type AmfInfo struct {

	AmfSetId string `json:"amfSetId"`

	AmfRegionId string `json:"amfRegionId"`

	GuamiList []Guami `json:"guamiList"`

	TaiList []Tai `json:"taiList,omitempty"`

	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`

	BackupInfoAmfFailure []Guami `json:"backupInfoAmfFailure,omitempty"`

	BackupInfoAmfRemoval []Guami `json:"backupInfoAmfRemoval,omitempty"`

	N2InterfaceAmfInfo N2InterfaceAmfInfo `json:"n2InterfaceAmfInfo,omitempty"`
}
