/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DefaultNotificationSubscription - Data structure for specifying the notifications the NF service subscribes by default along with callback URI
type DefaultNotificationSubscription struct {

	NotificationType NotificationType `json:"notificationType"`

	CallbackUri string `json:"callbackUri"`

	N1MessageClass N1MessageClass `json:"n1MessageClass,omitempty"`

	N2InformationClass N2InformationClass `json:"n2InformationClass,omitempty"`

	Versions []string `json:"versions,omitempty"`
}
