/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PcfInfo - Information of a PCF NF Instance
type PcfInfo struct {

	GroupId string `json:"groupId,omitempty"`

	DnnList []string `json:"dnnList,omitempty"`

	SupiRanges []SupiRange `json:"supiRanges,omitempty"`

	GpsiRanges []IdentityRange `json:"gpsiRanges,omitempty"`

	RxDiamHost string `json:"rxDiamHost,omitempty"`

	RxDiamRealm string `json:"rxDiamRealm,omitempty"`

	V2xSupportInd bool `json:"v2xSupportInd,omitempty"`
}
