/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0.alpha-4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Ipv4AddressRange - Range of IPv4 addresses
type Ipv4AddressRange struct {

	Start string `json:"start,omitempty"`

	End string `json:"end,omitempty"`
}
